---
- name: Install Apache web server
  apt: name=apache2 state=present

- name: Start Apache service
  service:
    name: apache2
    state: started

- name: Restart Apache service
  service:
    name: apache2
    state: restarted
