---
- name: Modification du fichier grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="net.ifnames=0"'
  notify: Redemarrer grub

- name: Redémarrer grub
  command: grub-mkconfig -o /boot/grub/grub.cfg
  async: 0
  poll: 0
  ignore_errors: yes

- name: Redémarrage de grub
  shell: update-grub
  async: 0
  poll: 0
  ignore_errors: yes
  register: result_grub
  notify: Modifier fichier interfaces

- name: Mise à jour du serveur
  apt:
    update_cache: yes
    upgrade: dist
  when: "'CHANGED' in result_grub.stdout"
  notify: Installation de XiVO
